// 食材タグ定義
const INGREDIENT_TAGS = [
  { id: 'fish',        label: '魚' },
  { id: 'chicken',     label: '鶏肉' },
  { id: 'pork',        label: '豚肉' },
  { id: 'beef',        label: '牛肉' },
  { id: 'ground_meat', label: 'ひき肉' },
  { id: 'shrimp',      label: 'えび' },
  { id: 'tofu',        label: '豆腐' },
  { id: 'egg',         label: '卵' },
  { id: 'vegetable',   label: '野菜' },
  { id: 'seaweed',     label: '海藻' },
  { id: 'mushroom',    label: 'きのこ' },
  { id: 'potato',      label: 'じゃがいも' },
  { id: 'dairy',       label: '乳製品' },
];

// mealTime 値:
//   'morning'      … 朝向け
//   'lunch_dinner' … 昼・夕向け
//   'any'          … いつでも

// 初期献立データ（主菜60品 + 副菜50品）
const INITIAL_DISHES = [

  // ==================== 主菜（朝食用）====================
  { name: '目玉焼き',               type: 'main', category: '和食', mealTime: 'morning',      ingredients: ['egg'],                    recipeUrl: null, recipeText: '', memo: '' },
  { name: 'スクランブルエッグ',     type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['egg', 'dairy'],           recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ハムエッグ',             type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['egg', 'pork'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ベーコンエッグ',         type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['egg', 'pork'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: '納豆ご飯',               type: 'main', category: '和食', mealTime: 'morning',      ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ウインナーソテー',       type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['pork'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '温泉卵',                 type: 'main', category: '和食', mealTime: 'morning',      ingredients: ['egg'],                    recipeUrl: null, recipeText: '', memo: '' },
  { name: '鮭フレーク丼',           type: 'main', category: '和食', mealTime: 'morning',      ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'アジの干物',             type: 'main', category: '和食', mealTime: 'morning',      ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'トースト',               type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['dairy'],                  recipeUrl: null, recipeText: '', memo: '' },
  { name: 'オムレツ',               type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['egg', 'dairy'],           recipeUrl: null, recipeText: '', memo: '' },
  { name: 'フレンチトースト',       type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['egg', 'dairy'],           recipeUrl: null, recipeText: '', memo: '' },
  { name: '卵かけご飯',             type: 'main', category: '和食', mealTime: 'morning',      ingredients: ['egg'],                    recipeUrl: null, recipeText: '', memo: '' },
  { name: 'お粥',                   type: 'main', category: '和食', mealTime: 'morning',      ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'おにぎり',               type: 'main', category: '和食', mealTime: 'morning',      ingredients: ['seaweed'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: 'パンケーキ',             type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['egg', 'dairy'],           recipeUrl: null, recipeText: '', memo: '' },
  { name: 'サンドイッチ',           type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['egg'],                    recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ヨーグルトグラノーラ',   type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['dairy'],                  recipeUrl: null, recipeText: '', memo: '' },
  { name: '焼きおにぎり',           type: 'main', category: '和食', mealTime: 'morning',      ingredients: ['seaweed'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ツナサンド',             type: 'main', category: '洋食', mealTime: 'morning',      ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },

  // ==================== 主菜（和食・昼夕）====================
  { name: '鮭の塩焼き',             type: 'main', category: '和食', mealTime: 'any',          ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '鯖の味噌煮',             type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ぶりの照り焼き',         type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'さんまの塩焼き',         type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '鯵の南蛮漬け',           type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'いわしの梅煮',           type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ぶり大根',               type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['fish', 'vegetable'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: 'たらの西京焼き',         type: 'main', category: '和食', mealTime: 'any',          ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '鮭のちゃんちゃん焼き',   type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['fish', 'vegetable'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: '鶏の唐揚げ',             type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['chicken'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: '鶏の照り焼き',           type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['chicken'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: '鶏の竜田揚げ',           type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['chicken'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: '鶏のみぞれ煮',           type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['chicken'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: '鶏もも肉の煮物',         type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['chicken'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: '親子丼',                 type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['chicken', 'egg'],         recipeUrl: null, recipeText: '', memo: '' },
  { name: '豚の生姜焼き',           type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['pork'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '豚バラ大根',             type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['pork', 'vegetable'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: '豚の角煮',               type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['pork'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '豚バラとキャベツの蒸し煮', type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['pork', 'vegetable'],   recipeUrl: null, recipeText: '', memo: '' },
  { name: '豚しゃぶ',               type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['pork'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '肉じゃが',               type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['pork', 'potato'],         recipeUrl: null, recipeText: '', memo: '' },
  { name: '牛肉のしぐれ煮',         type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['beef'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'すき焼き',               type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['beef'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '豚肉と野菜の炒め物',     type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['pork', 'vegetable'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: '豆腐ステーキ',           type: 'main', category: '和食', mealTime: 'lunch_dinner', ingredients: ['tofu'],                   recipeUrl: null, recipeText: '', memo: '' },

  // ==================== 主菜（洋食・昼夕）====================
  { name: 'ハンバーグ',             type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['ground_meat'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: 'チキンカレー',           type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['chicken'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ポークカレー',           type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['pork'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'グラタン',               type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['chicken', 'dairy'],       recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ミートソーススパゲッティ', type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['ground_meat'],          recipeUrl: null, recipeText: '', memo: '' },
  { name: 'オムライス',             type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['chicken', 'egg'],         recipeUrl: null, recipeText: '', memo: '' },
  { name: 'チキンソテー',           type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['chicken'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ポークソテー',           type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['pork'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'コロッケ',               type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['pork', 'potato'],         recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ロールキャベツ',         type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['ground_meat', 'vegetable'], recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ビーフシチュー',         type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['beef'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'クリームシチュー',       type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['chicken', 'dairy'],       recipeUrl: null, recipeText: '', memo: '' },
  { name: '鶏のピカタ',             type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['chicken', 'egg'],         recipeUrl: null, recipeText: '', memo: '' },
  { name: '白身魚フライ',           type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['fish'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ミートボール煮込み',     type: 'main', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['ground_meat'],            recipeUrl: null, recipeText: '', memo: '' },

  // ==================== 主菜（中華・昼夕）====================
  { name: '麻婆豆腐',               type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['pork', 'tofu'],           recipeUrl: null, recipeText: '', memo: '' },
  { name: '酢豚',                   type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['pork'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '回鍋肉',                 type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['pork', 'vegetable'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: '青椒肉絲',               type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['pork', 'vegetable'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: '八宝菜',                 type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['pork', 'vegetable'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: '餃子',                   type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['pork'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'エビチリ',               type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['shrimp'],                 recipeUrl: null, recipeText: '', memo: '' },
  { name: '豚キムチ炒め',           type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['pork'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'チンジャオロース',       type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['beef', 'vegetable'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: '豚肉と野菜の中華炒め',   type: 'main', category: '中華', mealTime: 'lunch_dinner', ingredients: ['pork', 'vegetable'],      recipeUrl: null, recipeText: '', memo: '' },

  // ==================== 副菜（和食）====================
  { name: 'ほうれん草のおひたし',   type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: '小松菜のお浸し',         type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ほうれん草の胡麻和え',   type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: '白和え',                 type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable', 'tofu'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ひじきの煮物',           type: 'side', category: '和食', mealTime: 'any',          ingredients: ['seaweed'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: 'きんぴらごぼう',         type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: '蓮根のきんぴら',         type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: '切り干し大根の煮物',     type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'かぼちゃの煮物',         type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: '里芋の煮物',             type: 'side', category: '和食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'なすの煮浸し',           type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: '小松菜と油揚げの煮物',   type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable', 'tofu'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: '厚揚げの煮物',           type: 'side', category: '和食', mealTime: 'any',          ingredients: ['tofu'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'こんにゃくの炒り煮',     type: 'side', category: '和食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'だし巻き卵',             type: 'side', category: '和食', mealTime: 'any',          ingredients: ['egg'],                    recipeUrl: null, recipeText: '', memo: '' },
  { name: '冷奴',                   type: 'side', category: '和食', mealTime: 'any',          ingredients: ['tofu'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: '煮卵',                   type: 'side', category: '和食', mealTime: 'any',          ingredients: ['egg'],                    recipeUrl: null, recipeText: '', memo: '' },
  { name: 'きゅうりの酢の物',       type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'わかめの酢の物',         type: 'side', category: '和食', mealTime: 'any',          ingredients: ['seaweed'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: '春雨サラダ',             type: 'side', category: '和食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ごぼうサラダ',           type: 'side', category: '和食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'にんじんのしりしり',     type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: '大根サラダ',             type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ポテトサラダ',           type: 'side', category: '和食', mealTime: 'lunch_dinner', ingredients: ['potato'],                 recipeUrl: null, recipeText: '', memo: '' },
  { name: '漬物',                   type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: '豆腐の味噌汁',           type: 'side', category: '和食', mealTime: 'any',          ingredients: ['tofu'],                   recipeUrl: null, recipeText: '', memo: '' },
  { name: 'わかめの味噌汁',         type: 'side', category: '和食', mealTime: 'any',          ingredients: ['seaweed'],                recipeUrl: null, recipeText: '', memo: '' },
  { name: 'なすの味噌汁',           type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'じゃがいもの味噌汁',     type: 'side', category: '和食', mealTime: 'any',          ingredients: ['potato'],                 recipeUrl: null, recipeText: '', memo: '' },
  { name: '玉ねぎの味噌汁',         type: 'side', category: '和食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },

  // ==================== 副菜（洋食）====================
  { name: 'コールスロー',           type: 'side', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'グリーンサラダ',         type: 'side', category: '洋食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'トマトサラダ',           type: 'side', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ブロッコリーのサラダ',   type: 'side', category: '洋食', mealTime: 'any',          ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'マカロニサラダ',         type: 'side', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['dairy', 'vegetable'],     recipeUrl: null, recipeText: '', memo: '' },
  { name: 'キャベツとツナのサラダ', type: 'side', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['vegetable', 'fish'],      recipeUrl: null, recipeText: '', memo: '' },
  { name: 'コーンスープ',           type: 'side', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'かぼちゃスープ',         type: 'side', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ミネストローネ',         type: 'side', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },
  { name: 'オニオンスープ',         type: 'side', category: '洋食', mealTime: 'lunch_dinner', ingredients: ['vegetable'],              recipeUrl: null, recipeText: '', memo: '' },

  // ==================== 副菜（その他）====================
  { name: 'もやしのナムル',         type: 'side', category: 'その他', mealTime: 'lunch_dinner', ingredients: ['vegetable'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ほうれん草のナムル',     type: 'side', category: 'その他', mealTime: 'any',          ingredients: ['vegetable'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: 'キャロットラペ',         type: 'side', category: 'その他', mealTime: 'lunch_dinner', ingredients: ['vegetable'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: 'アスパラのソテー',       type: 'side', category: 'その他', mealTime: 'lunch_dinner', ingredients: ['vegetable'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: 'ブロッコリーのおひたし', type: 'side', category: 'その他', mealTime: 'any',          ingredients: ['vegetable'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: 'もやし炒め',             type: 'side', category: 'その他', mealTime: 'lunch_dinner', ingredients: ['vegetable'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: 'エリンギのソテー',       type: 'side', category: 'その他', mealTime: 'lunch_dinner', ingredients: ['mushroom'],             recipeUrl: null, recipeText: '', memo: '' },
  { name: 'きのこのマリネ',         type: 'side', category: 'その他', mealTime: 'lunch_dinner', ingredients: ['mushroom'],             recipeUrl: null, recipeText: '', memo: '' },
  { name: '枝豆',                   type: 'side', category: 'その他', mealTime: 'lunch_dinner', ingredients: ['vegetable'],            recipeUrl: null, recipeText: '', memo: '' },
  { name: 'とうもろこしのバター醤油炒め', type: 'side', category: 'その他', mealTime: 'lunch_dinner', ingredients: ['vegetable'],     recipeUrl: null, recipeText: '', memo: '' },
];

// 既存Firestoreデータへの mealTime 移行マップ（名前で照合）
const MEAL_TIME_MAP = {};
INITIAL_DISHES.forEach(d => { MEAL_TIME_MAP[d.name] = d.mealTime; });
